# Generated by Django 3.1.4 on 2021-01-07 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=128)),
                ('Description', models.TextField()),
                ('Creation_Date', models.DateField()),
                ('ClassCode', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Attachment', models.FileField(upload_to='')),
                ('TimeStamp', models.DateTimeField()),
                ('Classroom_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=128)),
                ('LastName', models.CharField(max_length=128)),
                ('DoB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Registration_Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='user_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=128)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user')),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('TaskID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('Description', models.TextField()),
                ('Creation_Date', models.DateTimeField()),
                ('LastModified', models.DateTimeField()),
                ('Classroom_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
                ('Content_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.content')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='submission',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Time_stamp', models.DateTimeField()),
                ('Last_modified', models.DateTimeField()),
                ('CLassroom_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
                ('Content_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.content')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Class_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.TextField()),
                ('TimeStamp', models.DateTimeField()),
                ('Description', models.TextField()),
                ('LastModified', models.DateTimeField()),
                ('Classroom_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
                ('Content_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.content')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user')),
            ],
        ),
        migrations.AddField(
            model_name='content',
            name='User_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user'),
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TimeStamp', models.DateTimeField()),
                ('LastModified', models.DateTimeField()),
                ('Content', models.TextField()),
                ('Classroom_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
                ('Post_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.post')),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='Creator_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.user'),
        ),
        migrations.CreateModel(
            name='analytic',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Generation_Time', models.DateTimeField()),
                ('Report', models.FileField(upload_to='')),
                ('CLassroom_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.classroom')),
                ('Teacher_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hyperion.teacher')),
            ],
        ),
    ]
