# Generated by Django 3.1.4 on 2021-01-08 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='Creation_Date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
